\getenv migration_password HELM_MIGRATION_PASSWORD
\getenv api_password HELM_API_PASSWORD
\getenv keycloak_password HELM_KEYCLOAK_PASSWORD

CREATE ROLE helm_migration LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
  PASSWORD :'migration_password';
CREATE ROLE helm_api LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
  PASSWORD :'api_password';
CREATE ROLE keycloak LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
  PASSWORD :'keycloak_password';
CREATE DATABASE helm OWNER helm_migration;
CREATE DATABASE keycloak OWNER keycloak;
REVOKE ALL ON DATABASE helm FROM PUBLIC;
REVOKE ALL ON DATABASE keycloak FROM PUBLIC;
GRANT CONNECT ON DATABASE helm TO helm_api;
REVOKE CONNECT ON DATABASE postgres, template1 FROM PUBLIC;

\connect helm
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO helm_api;
ALTER DEFAULT PRIVILEGES FOR ROLE helm_migration IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO helm_api;
ALTER DEFAULT PRIVILEGES FOR ROLE helm_migration IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO helm_api;

\connect keycloak
REVOKE ALL ON SCHEMA public FROM PUBLIC;
