from pathlib import Path
p=Path('backend/api/widget/test/continuation.mjs')
s=p.read_text(encoding='utf-8')
s=s.replace('idleCloseAt: null, closeReason: null,', "idleCloseAt: null, idleTimeoutSeconds: 300, idleWarningAt: null, cleanupState: 'NONE', cleanupError: null, closeReason: null,")
s=s.replace("idleCloseAt: new Date(Date.now() + 299000).toISOString()", "idleCloseAt: new Date(Date.now() + 59000).toISOString(), idleWarningAt: new Date(Date.now() - 1000).toISOString()")
s=s.replace("idleCloseAt: new Date(Date.now() + 900000).toISOString()", "idleCloseAt: new Date(Date.now() + 300000).toISOString(), idleWarningAt: new Date(Date.now() + 240000).toISOString()")
s=s.replace("'Five-minute warning is visible with session details folded'", "'One-minute warning uses the server deadline with session details folded'")
s=s.replace('/4:5/', '/0:5/')
p.write_text(s,encoding='utf-8',newline='\n')
p=Path('backend/api/widget/test/viewer-freeze.mjs')
s=p.read_text(encoding='utf-8').replace('  const document = {', "  const document = {\n    addEventListener: (type, callback) => listeners.set('document:' + type, callback),")
p.write_text(s,encoding='utf-8',newline='\n')
p=Path('backend/browser-node/src/server.ts')
s=p.read_text(encoding='utf-8').replace('\n      \n', '\n\n')
p.write_text(s,encoding='utf-8',newline='\n')
