bind 0.0.0.0
port 6379
protected-mode yes
aclfile /run/helm/users.acl
dir /data
appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite no
aof-use-rdb-preamble yes
save ""
maxmemory 512mb
maxmemory-policy noeviction
timeout 300
tcp-keepalive 60
loglevel warning
logfile ""
daemonize no
supervised no
enable-protected-configs no
enable-debug-command no
enable-module-command no
