auth_request /oauth2/auth;
auth_request_set $access_token $upstream_http_x_auth_request_access_token;
auth_request_set $auth_cookie $upstream_http_set_cookie;
add_header Set-Cookie $auth_cookie always;
proxy_set_header Authorization "Bearer $access_token";
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto $public_scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Helm-Channel WEB;
proxy_pass http://helm_api;
