import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const workerDirectory = new URL('../browser-worker/', import.meta.url);
const requireFromWorker = createRequire(new URL('package.json', workerDirectory));
const { z } = requireFromWorker('zod');
const compiler = requireFromWorker.resolve('typescript/bin/tsc');
execFileSync(process.execPath, [compiler, '-p', fileURLToPath(new URL('tsconfig.json', workerDirectory))], {
  cwd: fileURLToPath(workerDirectory), stdio: 'inherit', timeout: 120_000,
});
const modules = await Promise.all(['protocol', 'enrollment', 'artifact-transfer'].map((name) =>
  import(new URL(`dist/src/${name}.js`, workerDirectory))));
const schemas = Object.assign({}, ...modules);
const outputDirectory = new URL('schemas/', import.meta.url);
const check = process.argv.includes('--check');
await mkdir(outputDirectory, { recursive: true });

for (const [name, validator] of Object.entries(schemas).sort(([left], [right]) => left.localeCompare(right))) {
  if (!name.endsWith('Schema')) continue;
  const basename = name.replace(/Schema$/, '').replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
  const schema = z.toJSONSchema(validator, { target: 'draft-2020-12', io: 'input' });
  const document = `${JSON.stringify({
    ...schema,
    $id: `urn:helmglass:worker:v1:${basename}`,
    $comment: 'Generated by backend/worker-protocol/generate.mjs from the strict worker boundary schemas. Do not edit manually.',
  }, null, 2)}\n`;
  const path = new URL(`${basename}.schema.json`, outputDirectory);
  if (check) {
    const existing = await readFile(path, 'utf8');
    if (existing !== document) throw new Error(`Generated protocol schema is stale: ${basename}`);
  } else {
    await writeFile(path, document, 'utf8');
  }
  process.stdout.write(`${check ? 'Verified' : 'Generated'} ${basename}.schema.json\n`);
}
